import {test} from 'node:test';import assert from 'node:assert/strict';import {sample} from '../lib/samples.ts';import {calculate,validateDecision,reviseOffer} from '../lib/model.ts';
const ev={reference:'SYNTHETIC quote',observedAt:'2026-10-02'};
function decision(){const d=sample('en');const o=d.offers[2];const evaluation=structuredClone(o.evaluation);evaluation.costs.find(c=>c.kind==='freight').amount=4000;o.routes=[{id:'economy',label:'Economy example',provider:'Example provider',warehouseReference:'Confirmed receiving reference (example)',quoteQuantity:4,freight:null,evaluation,arrival:{version:1,kind:'direct',scope:'door',startDate:'2026-10-02',validUntil:'2026-10-09',legs:[{id:'door',stage:'door',dependsOn:[],minDays:8,maxDays:12,calendar:{kind:'calendar',weekend:[],holidays:[],reference:'Calendar days'},evidence:ev}]}}];o.selectedRouteId='economy';return d}
test('selected route changes cost and complete ETA without mutating base quote',()=>{const d=validateDecision(decision());const r=calculate(d,'2026-10-02')[2];assert.equal(r.total,28700);assert.equal(r.offer.days,12);assert.equal(d.offers[2].evaluation.costs.find(c=>c.kind==='freight').amount,6500);assert.equal(d.offers[2].selectedRouteId,'economy')});
test('missing route ETA cannot borrow baseline days or recommend',()=>{const d=decision();d.offers[2].routes[0].arrival=null;const r=calculate(validateDecision(d),'2026-10-02')[2];assert.equal(r.offer.days,null);assert.equal(r.eligible,false)});
test('selected route quantity mismatch cannot inherit baseline complete total',()=>{const d=decision();d.offers[2].routes[0].quoteQuantity=2;assert.equal(calculate(validateDecision(d),'2026-10-02')[2].total,null)});
test('invalid and duplicate route identities rejected on import',()=>{const d=decision();d.offers[2].selectedRouteId='missing';assert.throws(()=>validateDecision(d));d.offers[2].selectedRouteId='economy';d.offers[2].routes.push(d.offers[2].routes[0]);assert.throws(()=>validateDecision(d))});
test('editing core product fields retains but invalidates all route evidence',()=>{const d=decision(),o=d.offers[2];const next=reviseOffer(o,{...o,unitPrice:99});assert.equal(next.routes.length,1);assert.equal(next.routes[0].evaluation.reviewRequired,true)});
test('future order date includes waiting time when enforcing the buyer deadline',()=>{const d=decision();d.maxDays=14;d.offers[2].routes[0].arrival.startDate='2026-10-20';const r=calculate(validateDecision(d),'2026-10-02')[2];assert.equal(r.offer.days,30);assert.equal(r.eligible,false);assert.ok(r.reasons.includes('deadline'))});
