import {useMemo} from 'react';
import {compareOptions,comparableSavings,type Option} from '@/lib/optimization';
import {selectTiers,type Decision,type Locale} from '@/lib/model';
import {evaluationCopy} from '@/lib/evaluation-copy';
import {shippingCopy} from '@/lib/shipping-copy';
import {dictionaries} from '@/lib/i18n';
const copy={
 en:{savings:'Less than the original quote · same item, quantity and dated evidence',title:'Compare routes and quantities',intro:'Only supplied quantity quotes are compared. Budget and tier choices use the upper cost bound. An option is outperformed only at the same quantity, with no worse supported quality or timing and a definitely lower cost or another measured improvement.',apply:'Use this option',selected:'Selected',purchased:'purchased',needed:'needed',quality:'Quality',all:'All supplied options',outperformed:'Outperformed on cost, quality and timing',pending:'Not qualified',none:'No qualified route and quantity combination yet.'},
 ru:{savings:'Дешевле исходного предложения · тот же товар, количество и даты источников',title:'Сравнить маршруты и количество',intro:'Сравниваются только предоставленные предложения на конкретное количество. Бюджет и выбор учитывают верхнюю стоимость. Вариант уступает другому только при равном количестве, не худшем качестве и сроке и определённом улучшении цены или другого показателя.',apply:'Выбрать вариант',selected:'Выбран',purchased:'к покупке',needed:'нужно',quality:'Качество',all:'Все предоставленные варианты',outperformed:'Уступает по стоимости, качеству и сроку',pending:'Не соответствует условиям',none:'Пока нет подходящего сочетания маршрута и количества.'},
 hy:{savings:'Սկզբնական առաջարկից ցածր է · նույն ապրանքը, քանակն ու աղբյուրների ամսաթվերը',title:'Համեմատել երթուղիներն ու քանակները',intro:'Համեմատվում են միայն նշված քանակների համար տրամադրված առաջարկները։ Բյուջեն և ընտրությունը հաշվի են առնում վերին արժեքը։ Տարբերակը զիջում է միայն նույն քանակի դեպքում՝ ոչ ավելի վատ որակով ու ժամկետով և գնի կամ այլ ցուցանիշի հաստատված բարելավմամբ։',apply:'Ընտրել այս տարբերակը',selected:'Ընտրված է',purchased:'գնվող',needed:'անհրաժեշտ',quality:'Որակ',all:'Բոլոր տրամադրված տարբերակները',outperformed:'Զիջում է արժեքի, որակի և ժամկետի չափանիշներով',pending:'Չի համապատասխանում պայմաններին',none:'Դեռ չկա համապատասխան երթուղու և քանակի համադրություն։'},
};
export function OptionComparison({decision,locale,asOf,onApply}:{decision:Decision;locale:Locale;asOf:string;onApply:(option:Option)=>void}){
 const c=copy[locale],t=dictionaries[locale],et=evaluationCopy[locale],st=shippingCopy[locale];
 const options=useMemo(()=>compareOptions(decision,asOf),[decision,asOf]);
 const frontier=options.filter(o=>o.result.eligible&&!o.dominated);
 const winners=selectTiers(frontier.map(o=>({...o.result,offer:{...o.result.offer,id:o.id}})));
 const choices=frontier.filter(o=>Object.values(winners).includes(o.id));
 const price=(o:Option)=>{const r=o.result,low=r.totalLow??r.subtotalLow,high=r.total??r.subtotal;const f=(n:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n);return (low===high?f(high):f(low)+' – '+f(high))+' AMD'};
 function row(o:Option,action:boolean){const savings=comparableSavings(o,options.find(b=>b.offerId===o.offerId&&!b.routeId));const r=o.result,base=decision.offers.find(x=>x.id===o.offerId)!,selected=base.selectedRouteId===o.routeId&&(base.purchaseQuantity??Math.ceil(decision.quantity/base.packSize)*base.packSize)===o.quantity;return <article className="option-row" key={o.id}><div><strong>{r.offer.name}</strong><p>{r.route?.route.label??st.base} · {r.route?.route.provider??r.offer.seller}</p><small>{o.quantity} {c.purchased} / {decision.quantity} {c.needed}</small></div><div><small>{r.total===null?t.subtotal:t.total}</small><strong className="option-price">{price(o)}</strong><p>{c.quality}: {r.qualityScore??'—'} / 100 · {r.offer.days??'—'} {t.days}</p>{savings&&<p className="option-savings">{savings.low===savings.high?savings.low:savings.low+' – '+savings.high} AMD · {c.savings}</p>}<small>{!r.eligible?c.pending:o.dominated?c.outperformed:([['premium',t.premium],['value',t.value],['budget',t.budgetTier]] as const).filter(([key])=>winners[key]===o.id).map(([,label])=>label).join(' · ')}</small></div>{action&&<button type="button" className="button outline" disabled={selected} onClick={()=>onApply(o)}>{selected?c.selected:c.apply}</button>}</article>}
 if(!decision.offers.length)return null;
 return <details className="option-comparison"><summary>{c.title} <span className="count">{options.length}</span></summary><p className="small muted">{c.intro}</p>{choices.length?choices.map(o=>row(o,true)):<p>{c.none}</p>}<details className="option-all"><summary>{c.all}</summary>{options.map(o=>row(o,o.result.eligible))}</details><p className="small muted">{et.rangePolicy}</p></details>;
}
