'use client';
import {useState,useEffect,useRef,useMemo,type FormEvent,type ReactNode} from 'react';
import {ShoppingBag,LayoutDashboard,Bookmark,Truck,Globe2,Wallet,Plus,ArrowUpRight,Check,CheckCircle2,AlertCircle,Package,MapPin,SlidersHorizontal,Download,Upload,X,Trash2,Copy,ExternalLink,Menu,Search,ChevronRight,Sparkles,ShieldCheck,Clock,FileText,LogOut,Printer} from 'lucide-react';
import {calculate,validateDecision,type Decision,type Offer,type Locale,type Result} from '@/lib/model';
import {sample} from '@/lib/samples';
import {dictionaries,type Copy as Words} from '@/lib/i18n';
type View='workspace'|'saved'|'sources'|'connection'|'plans';
type Saved={id:string;title:string;decision:Decision;updated:string};
const money=(n:number,locale:Locale)=>new Intl.NumberFormat(locale==='hy'?'hy-AM':locale==='ru'?'ru-AM':'en-AM',{maximumFractionDigits:0}).format(n);
function Modal({title,closeLabel,onClose,children}:{title:string;closeLabel:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><header className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label={closeLabel} onClick={onClose}><X size={22}/></button></header><div className="modal-body">{children}</div></dialog>}
export default function Workspace({user,signInPath}:{user:{id:string;name:string}|null;signInPath:string}){
 const [ready,setReady]=useState(false);const [locale,setLocale]=useState<Locale>('en'),[view,setView]=useState<View>('workspace'),[decision,setDecision]=useState<Decision>(()=>sample('en')),[filter,setFilter]=useState('all'),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState<Saved[]>([]),[loading,setLoading]=useState(false),[savedSearch,setSavedSearch]=useState(''),[detail,setDetail]=useState<string|null>(null),[editing,setEditing]=useState<Offer|null|undefined>(undefined),[privacy,setPrivacy]=useState(false),[draft,setDraft]=useState(false),[lastCall,setLastCall]=useState<string|null>(null),[recordId,setRecordId]=useState<string|undefined>(),[formError,setFormError]=useState('');
 const activeRecord=useRef<string|undefined>(undefined);const upload=useRef<HTMLInputElement>(null);const t=dictionaries[locale];const results=useMemo(()=>calculate(decision),[decision]);const eligible=results.filter(r=>r.eligible).sort((a,b)=>a.total!-b.total!);const best=eligible[0];const hasSamples=decision.offers.some(o=>o.evidence==='sample');const selected=results.find(r=>r.offer.id===detail);
 useEffect(()=>{const l=localStorage.getItem('yc-locale');if(l==='en'||l==='hy'||l==='ru')setLocale(l);try{const raw=sessionStorage.getItem('yc-draft');if(raw){const draft=JSON.parse(raw);if(draft.owner===null||draft.owner===user?.id){setDecision(validateDecision(draft.decision));if(user&&draft.owner===user.id&&typeof draft.id==='string'){activeRecord.current=draft.id;setRecordId(draft.id)}}else{sessionStorage.removeItem('yc-draft')}}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready){try{sessionStorage.setItem('yc-draft',JSON.stringify({decision,id:recordId,owner:user?.id??null}))}catch{}}},[decision,recordId,ready]);
 useEffect(()=>{document.documentElement.lang=locale;localStorage.setItem('yc-locale',locale)},[locale]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id)}},[toast]);
 const message=(code:string)=>t[code as keyof Words]??t.error;
 async function loadSaved(){if(!user)return;setLoading(true);try{const r=await fetch('/api/decisions');if(!r.ok)throw new Error();setSaved(await r.json())}catch{setToast(t.error)}finally{setLoading(false)}}
 async function refreshConnection(){try{const r=await fetch('/api/session');if(!r.ok)throw new Error();const data=await r.json() as {lastCall:string|null};setLastCall(data.lastCall)}catch{setToast(t.error)}}
 useEffect(()=>{if(view==='saved')void loadSaved();if(view==='connection')void refreshConnection()},[view]);
 function navigate(v:View){setView(v);setMenu(false);setFormError('')}
 function setField(key:keyof Decision,value:string){setDecision(d=>({...d,[key]:key==='title'?value:Number(value)}));setFormError('')}
 function fresh(){if(decision.offers.length&&!confirm(t.clearConfirm))return;setDecision({version:1,title:t.blank,quantity:1,maxQuantity:1,budget:50000,maxDays:21,offers:[]});activeRecord.current=undefined;setRecordId(undefined);setFilter('all');navigate('workspace')}
 async function save(){if(!user){setToast(t.auth);return}setSaving(true);try{const d=validateDecision(decision);const key=activeRecord.current??crypto.randomUUID();activeRecord.current=key;setRecordId(key);const r=await fetch('/api/decisions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:d,id:key})});const data=await r.json() as {id:string;error:string};if(!r.ok)throw new Error(data.error);if(activeRecord.current===key)setRecordId(data.id);setToast(t.saveSuccess)}catch(e){setToast(message(e instanceof Error?e.message:'error'))}finally{setSaving(false)}}
 function exportData(){try{const d=validateDecision(decision);const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='yerevan-cart-comparison.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setToast(t.invalid)}}
 async function importData(file:File|undefined){if(!file)return;if(file.size>100000){setToast(t.tooLarge);return}try{const d=validateDecision(JSON.parse(await file.text()));setDecision(d);activeRecord.current=undefined;setRecordId(undefined);setFilter('all');navigate('workspace')}catch{setToast(t.invalidFile)}finally{if(upload.current)upload.current.value=''}}
 async function removeSaved(id:string){if(!confirm(t.deleteConfirm))return;try{const r=await fetch('/api/decisions?id='+encodeURIComponent(id),{method:'DELETE'});if(!r.ok)throw new Error();setSaved(old=>old.filter(d=>d.id!==id));if(recordId===id){activeRecord.current=undefined;setRecordId(undefined);}setToast(t.deleteSuccess)}catch{setToast(t.error)}}
 async function deleteAll(){if(!confirm(t.deleteAllConfirm))return;try{const r=await fetch('/api/decisions');if(!r.ok)throw new Error();const all:Saved[]=await r.json();for(const d of all){const res=await fetch('/api/decisions?id='+encodeURIComponent(d.id),{method:'DELETE'});if(!res.ok)throw new Error()}setSaved([]);activeRecord.current=undefined;setRecordId(undefined);setToast(t.allDeleted)}catch{setToast(t.error)}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setToast(t.copied)}catch{setToast(t.error)}}
 const nav:[View,typeof ShoppingBag][]=[['workspace',LayoutDashboard],['saved',Bookmark],['sources',Truck],['connection',Sparkles],['plans',Wallet]];
 const labelFor=(s:Offer['source'])=>t[s];
 return <div className="app-shell">
 <a className="skip" href="#main">{t.workspace}</a>
 {menu&&<button className="nav-backdrop" onClick={()=>setMenu(false)} aria-label={t.close}/>}
 <aside className={'sidebar '+(menu?'is-open':'')}>
 <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('workspace')}}><span className="brand-icon"><ShoppingBag size={24}/></span><span>Yerevan<span className="brand-light"> Cart</span><small>{t.tagline}</small></span></a>
 <button className="new-button" onClick={fresh}><Plus size={18}/>{t.newComparison}</button>
 <div className="nav-label">YEREVAN CART</div>
 <nav>{nav.map(([v,Icon])=><button key={v} className={view===v?'nav-item active':'nav-item'} aria-current={view===v?'page':undefined} onClick={()=>navigate(v)}><Icon size={20}/><span>{t[v]}</span>{v==='workspace'&&<span className="nav-mark"/>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="chat-mini"><Sparkles size={22}/><h3>{t.connection}</h3><p>{t.step3Body}</p><button onClick={()=>navigate('connection')}>{t.help}<ChevronRight size={16}/></button></div><button className="privacy-link" onClick={()=>setPrivacy(true)}><ShieldCheck size={17}/>{t.privacy}</button><div className="sidebar-location"><MapPin size={16}/>{t.city}</div></div>
 </aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Menu" onClick={()=>setMenu(!menu)}><Menu size={22}/></button><span>Yerevan Cart</span><ChevronRight size={14}/><strong>{t[view]}</strong></div><div className="top-actions"><label className="language"><Globe2 size={16}/><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">English</option><option value="hy">Հայերեն</option><option value="ru">Русский</option></select></label>{user?<a className="avatar" href="/signout-with-chatgpt?return_to=/" target="_top" onClick={()=>sessionStorage.removeItem('yc-draft')} title={t.signout} aria-label={t.signout}>{user.name.slice(0,1).toUpperCase()}</a>:<a className="signin" href={signInPath} target="_top">{t.signin}</a>}</div></header>
 <main id="main">
 {view==='workspace'&&<>
 <div className="page-heading"><div><div className="eyebrow"><span className="line"/>{t.city}</div><h1>{t.greeting}</h1><p>{t.intro}</p></div><span className="pill subtle">{t.preview}</span></div>
 <form className="brief-card" onSubmit={e=>{e.preventDefault();try{validateDecision(decision);setFormError('');document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'})}catch{setFormError(t.invalid)}}}>
 <label className="brief-title"><span>{t.what}</span><div className="input-icon"><Search size={21}/><input maxLength={180} value={decision.title} onChange={e=>setField('title',e.target.value)} required/></div></label>
 <div className="brief-fields"><label>{t.quantity}<input type="number" min={1} max={10000} step={1} value={decision.quantity||''} onChange={e=>setField('quantity',e.target.value)} required/></label><label>{t.maxQuantity}<input type="number" min={decision.quantity||1} max={10000} value={decision.maxQuantity||''} onChange={e=>setField('maxQuantity',e.target.value)} required/></label><label>{t.budget}<input type="number" min={1} max={1000000000} value={decision.budget||''} onChange={e=>setField('budget',e.target.value)} required/></label><label>{t.maxDays}<input type="number" min={1} max={365} value={decision.maxDays||''} onChange={e=>setField('maxDays',e.target.value)} required/></label><button className="button primary" type="submit"><SlidersHorizontal size={17}/>{t.compare}</button></div>
 {formError&&<p role="alert" className="error-text">{formError}</p>}
 </form>
 <div className={'provenance '+(hasSamples?'':'manual-provenance')}><div><FileText size={19}/><p><strong>{hasSamples?t.sample:t.manualMode}</strong><span>{hasSamples?t.sampleNotice:t.manualNotice}</span></p></div><button onClick={()=>{setDecision(sample(locale));activeRecord.current=undefined;setRecordId(undefined);setFilter('all')}}>{t.sampleLoad}</button></div>
 <section className="metrics" aria-label={t.offers}><div><span>{t.offers}</span><strong>{decision.offers.length.toString().padStart(2,'0')}<Package size={21}/></strong></div><div><span>{t.qualified}</span><strong>{eligible.length.toString().padStart(2,'0')}<CheckCircle2 size={21}/></strong></div><div><span>{t.bestPrice}</span><strong className="price-metric">{best?money(best.total!,locale):'—'}<small>AMD</small></strong></div><div><span>{t.pending}</span><strong>{results.filter(r=>!r.eligible).length.toString().padStart(2,'0')}<Clock size={21}/></strong></div></section>
 <div className="results-head" id="results"><div><h2>{t.offers}<span className="count">{decision.offers.length}</span></h2><div className="filter-row" aria-label={t.filter}>{(['all','local','alibaba','temu','other'] as const).map(s=><button className={filter===s?'filter selected':'filter'} key={s} onClick={()=>setFilter(s)}>{t[s]}</button>)}</div></div><button className="button outline" disabled={decision.offers.length>=20} onClick={()=>setEditing(null)}><Plus size={17}/>{t.addOffer}</button></div>
 {!results.length?<div className="empty-state"><Package size={44}/><h2>{t.empty}</h2><p>{t.emptyBody}</p><button className="button primary" onClick={()=>setEditing(null)}><Plus size={17}/>{t.addOffer}</button></div>:<div className="offer-grid">{results.filter(r=>filter==='all'||r.offer.source===filter).map(r=><article key={r.offer.id} className={'offer-card '+(best?.offer.id===r.offer.id?'winner ':'')+(!r.eligible?'provisional':'')}><div className={'card-ribbon '+r.offer.quality}>{r.offer.quality==='premium'?<Sparkles size={15}/>:r.offer.quality==='value'?<ShieldCheck size={15}/>:<Wallet size={15}/>}<span>{r.offer.quality==='budget'?t.budgetTier:t[r.offer.quality]}</span>{best?.offer.id===r.offer.id&&<Check size={16}/>}</div><div className="card-body"><div className="source-row"><span className={'source-symbol '+r.offer.source}>{r.offer.source==='local'?<MapPin size={19}/>:r.offer.source==='alibaba'?'a':r.offer.source==='temu'?'T':<Package size={19}/>}</span><div><strong>{labelFor(r.offer.source)}</strong><small>{r.offer.evidence==='sample'?t.sampleEvidence:r.offer.seller}</small></div></div><h3>{r.offer.name}</h3><div className="product-meta"><span><Package size={14}/>{r.quantity} {t.pieces}</span><span><Clock size={14}/>{r.offer.days??'—'} {t.days}</span></div><div className="price-block"><span>{r.total===null?t.subtotal:t.total}</span><strong>{money(r.total??r.subtotal,locale)}<small>AMD</small></strong><span>{r.perPiece===null?t.incomplete:money(r.perPiece,locale)+' AMD '+t.perPiece}</span></div><div className={'evidence-line '+(r.eligible?'good':'warning')}>{r.eligible?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}<span>{best?.offer.id===r.offer.id?t.lowest:r.eligible?t.complete:r.reasons.includes('incomplete')?t.incomplete:t.pending}</span></div><button className="details-button" onClick={()=>setDetail(r.offer.id)}>{t.details}<ChevronRight size={17}/></button></div></article>)}</div>}
 {results.length>0&&!results.some(r=>filter==='all'||r.offer.source===filter)&&<p className="empty-state">{t.noMatches}</p>}
 {results.length>0&&!best&&<p className="warning-note"><AlertCircle size={17}/>{t.noWinner}</p>}
 <div className="bottom-actions"><p><ShieldCheck size={18}/>{t.dataReminder}</p><div><button className="button plain" onClick={()=>upload.current?.click()}><Upload size={16}/>{t.import}</button><button className="button plain" onClick={exportData}><Download size={16}/>{t.export}</button><button className="button primary" onClick={save} disabled={!ready||saving||!decision.offers.length}><Bookmark size={16}/>{saving?t.saving:t.save}</button></div></div>
 {!user&&<div className="signin-note"><span>{t.auth}</span><a href={signInPath} target="_top">{t.signin}<ExternalLink size={14}/></a></div>}
 </>}
 {view==='saved'&&<><PageHeading title={t.saveTitle} text={t.saveIntro}/>{!user?<div className="empty-state"><Bookmark size={40}/><p>{t.auth}</p><a className="button primary" href={signInPath} target="_top">{t.signin}</a></div>:<><label className="saved-search"><Search size={18}/><input aria-label={t.searchSaved} placeholder={t.searchSaved} value={savedSearch} onChange={e=>setSavedSearch(e.target.value)}/></label>{loading?<p aria-live="polite">{t.loading}</p>:saved.length===0?<div className="empty-state"><Bookmark size={40}/><h2>{t.emptySaved}</h2><button className="button primary" onClick={()=>navigate('workspace')}>{t.workspace}</button></div>:<div className="saved-list">{saved.filter(d=>d.title.toLocaleLowerCase().includes(savedSearch.toLocaleLowerCase())).map(d=><article key={d.id}><div className="saved-icon"><ShoppingBag size={24}/></div><div><h3>{d.title}</h3><p>{d.decision.offers.length} {t.quoteCount} · {t.updated} {new Date(d.updated).toLocaleDateString(locale)}</p></div><button className="button outline" onClick={()=>{setDecision(validateDecision(d.decision));activeRecord.current=d.id;setRecordId(d.id);setFilter('all');navigate('workspace')}}>{t.open}</button><button className="icon-button danger" aria-label={t.delete} onClick={()=>removeSaved(d.id)}><Trash2 size={18}/></button></article>)}</div>}</>}</>}
 {view==='sources'&&<><PageHeading title={t.sourceTitle} text={t.sourceIntro}/><div className="source-grid">{(['local','alibaba','temu','forwarder'] as const).map(s=><article className="info-card" key={s}><div className="info-icon">{s==='forwarder'?<Truck/>:s==='local'?<MapPin/>:<Globe2/>}</div><h2>{t[s]}</h2><span className="pill subtle">{t.manual}</span><p>{s==='forwarder'?t.forwarderDesc:t.sourceDescription}</p><button className="button outline" onClick={()=>{navigate('workspace');setEditing(null)}}><Plus size={16}/>{t.addOffer}</button></article>)}</div><div className="notice"><ShieldCheck size={22}/><p>{t.sourcePolicy}</p></div></>}
 {view==='connection'&&<><PageHeading title={t.connectionTitle} text={t.connectionIntro}/><div className="connection-layout"><div><div className="steps">{[1,2,3].map((n)=><article key={n}><span className="step-number">0{n}</span><div><h2>{t[('step'+n) as keyof Words]}</h2><p>{t[('step'+n+'Body') as keyof Words]}</p>{n===1&&!user&&<a className="button primary" href={signInPath} target="_top">{t.signin}</a>}</div></article>)}</div><div className="endpoint"><label>{t.endpoint}</label><code>https://yerevan-cart.rezaiixhossein.chatgpt.site/mcp</code><button className="button outline" onClick={()=>copy('https://yerevan-cart.rezaiixhossein.chatgpt.site/mcp')}><Copy size={16}/>{t.copy}</button></div></div><aside className="connection-card"><Sparkles size={32}/><h2>ChatGPT + Yerevan Cart</h2><div className={'status-box '+(lastCall?'good':'')}><span>{lastCall?t.lastCall:t.notConnected}</span><strong>{lastCall?new Date(lastCall).toLocaleString(locale):t.unverified}</strong></div><button className="button outline" onClick={refreshConnection}>{t.refresh}</button><p>{t.connectionNote}</p><button className="button primary" onClick={()=>copy(t.prompt)}><Copy size={17}/>{t.copyPrompt}</button></aside></div></>}
 {view==='plans'&&<><PageHeading title={t.planTitle} text={t.planIntro}/><div className="plan-grid">{(['free','starter','frequent'] as const).map((p,i)=><article className={'plan-card '+(i===0?'current-plan':'')} key={p}><span className="pill subtle">{i===0?t.current:t.proposed}</span><h2>{t[p]}</h2><div className="plan-price">{i===0?t.freePrice:money(i===1?2900:6900,locale)}{i>0&&<small>AMD {t.month}</small>}</div><ul>{t[(p+'Features') as keyof Words].split('|').map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul>{i===0?<button className="button primary" onClick={()=>navigate('workspace')}>{t.workspace}</button>:<span className="disabled-plan">{t.notAvailable}</span>}</article>)}</div><div className="notice"><Wallet size={22}/><p>{t.planNote}</p></div></>}
 <footer><span>© 2026 Yerevan Cart</span><span>{t.public}</span><div><button onClick={()=>setPrivacy(true)}>{t.privacy}</button><a href="https://github.com/Hrezaii95/yerevan-Cart/issues" target="_blank" rel="noreferrer" title={t.supportText}>{t.support}<ExternalLink size={13}/></a></div></footer>
 </main></div>
 <input ref={upload} type="file" accept="application/json,.json" hidden onChange={e=>void importData(e.target.files?.[0])}/>
 {toast&&<div className="toast" role="status"><AlertCircle size={18}/>{toast}<button aria-label={t.close} onClick={()=>setToast('')}><X size={17}/></button></div>}
 {selected&&<Modal closeLabel={t.close} title={t.details} onClose={()=>setDetail(null)}><h3 className="detail-title">{selected.offer.name}</h3><p className="muted">{selected.offer.seller}</p><div className="breakdown">{([[t.needed,decision.quantity+' / '+selected.quantity],[t.snapshot,String(selected.offer.quoteQuantity??selected.quantity)],[t.goods,money(selected.goods,locale)+' AMD'],[t.freight,selected.offer.shipping===null?'—':money(selected.offer.shipping,locale)+' AMD'],[t.extra,selected.offer.fees===null?'—':money(selected.offer.fees,locale)+' AMD'],[selected.total===null?t.subtotal:t.total,money(selected.total??selected.subtotal,locale)+' AMD']] as [string,string][]).map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><p className="small muted">{t.snapshotNotice}</p>{selected.reasons.map(r=><p className="warning-note" key={r}><AlertCircle size={17}/>{t[(r+'Reason') as keyof Words]}</p>)}<div className="detail-evidence"><h3>{t.evidence}</h3><p>{selected.offer.evidence==='sample'?t.sampleEvidence:selected.offer.evidence==='quote'?t.quoteEvidence:t.userEvidence} · {selected.offer.observedAt}</p><p className="preserve">{selected.offer.notes||t.notesEmpty}</p>{selected.offer.url?<a href={selected.offer.url} target="_blank" rel="noreferrer">{t.openSource}<ExternalLink size={14}/></a>:<p className="muted">{t.sourceMissing}</p>}</div><div className="modal-actions"><button className="button outline" onClick={()=>{setEditing(selected.offer);setDetail(null)}}>{t.edit}</button><button className="button outline" onClick={()=>{setDraft(true);setDetail(null)}}>{t.draft}</button><button className="icon-button danger" aria-label={t.remove} onClick={()=>{if(confirm(t.removeConfirm)){setDecision(d=>({...d,offers:d.offers.filter(o=>o.id!==selected.offer.id)}));setDetail(null)}}}><Trash2 size={19}/></button></div></Modal>}
 {editing!==undefined&&<Modal closeLabel={t.close} title={editing?t.edit:t.addOffer} onClose={()=>setEditing(undefined)}><OfferForm offer={editing} quantity={decision.quantity} t={t} onCancel={()=>setEditing(undefined)} onSave={o=>{try{const d=validateDecision({...decision,offers:editing?decision.offers.map(v=>v.id===editing.id?o:v):[...decision.offers,o]});setDecision(d);setEditing(undefined)}catch{throw new Error('invalid')}}}/></Modal>}
 {privacy&&<Modal closeLabel={t.close} title={t.privacy} onClose={()=>setPrivacy(false)}><p className="legal-copy">{t.privacyText}</p>{user&&<button className="button outline danger" onClick={deleteAll}><Trash2 size={17}/>{t.deleteAll}</button>}</Modal>}
 {draft&&<Modal closeLabel={t.close} title={t.draft} onClose={()=>setDraft(false)}><p className="muted">{t.draftIntro}</p><textarea aria-label={t.draft} className="draft-area" readOnly value={t.draftText}/><button className="button primary" onClick={()=>copy(t.draftText)}><Copy size={17}/>{t.copy}</button></Modal>}
 </div>
}
function PageHeading({title,text}:{title:string;text:string}){return <div className="page-heading secondary-heading"><div><h1>{title}</h1><p>{text}</p></div></div>}
function OfferForm({offer,quantity,t,onSave,onCancel}:{offer:Offer|null;quantity:number;t:Words;onSave:(o:Offer)=>void;onCancel:()=>void}){const [error,setError]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),get=(key:string)=>String(f.get(key)??''),number=(key:string)=>get(key)===''?null:Number(get(key));try{onSave({id:offer?.id??crypto.randomUUID(),name:get('name'),seller:get('seller'),source:get('source') as Offer['source'],unitPrice:Number(get('unitPrice')),packSize:Number(get('packSize')),quoteQuantity:Number(get('quoteQuantity')),shipping:number('shipping'),fees:number('fees'),days:number('days'),quality:get('quality') as Offer['quality'],url:get('url'),observedAt:get('observedAt'),notes:get('notes'),evidence:offer?.evidence==='sample'?'sample':'user'})}catch{setError(true)}}
 const numeric=(name:string,label:string,min:number,nullable=false,max=100000000)=> <label>{label}<input name={name} type="number" min={min} max={max} step={name==='days'||name==='packSize'||name==='quoteQuantity'?1:'0.01'} defaultValue={offer?.[name as keyof Offer] as string|number??(nullable?'':name==='packSize'?1:name==='quoteQuantity'?quantity:'')} required={!nullable} placeholder={nullable?t.unknown:undefined}/></label>;
 return <form className="offer-form" onSubmit={submit}><label>{t.name}<input name="name" maxLength={180} defaultValue={offer?.name} required/></label><div className="form-grid"><label>{t.seller}<input name="seller" maxLength={120} defaultValue={offer?.seller} required/></label><label>{t.source}<select name="source" defaultValue={offer?.source??'local'}>{(['local','alibaba','temu','other'] as const).map(v=><option key={v} value={v}>{t[v]}</option>)}</select></label>{numeric('unitPrice',t.unitPrice,0)}{numeric('packSize',t.pack,1,false,10000)}{numeric('quoteQuantity',t.snapshot,1,false,10000)}{numeric('shipping',t.shipping,0,true)}{numeric('fees',t.fees,0,true)}{numeric('days',t.eta,0,true,365)}<label>{t.quality}<select name="quality" defaultValue={offer?.quality??'value'}><option value="value">{t.value}</option><option value="premium">{t.premium}</option><option value="budget">{t.budgetTier}</option></select></label></div><label>{t.url}<input name="url" type="url" maxLength={2000} defaultValue={offer?.url} placeholder="https://"/></label><label>{t.observed}<input name="observedAt" type="date" defaultValue={offer?.observedAt??new Date().toISOString().slice(0,10)} required/></label><label>{t.notes}<textarea name="notes" maxLength={3000} defaultValue={offer?.notes} rows={3}/></label>{error&&<p className="error-text" role="alert">{t.invalid}</p>}<div className="modal-actions"><button type="button" className="button outline" onClick={onCancel}>{t.cancel}</button><button className="button primary" type="submit">{offer?t.update:t.add}</button></div></form>}


