import {emptyEvaluation} from './evaluation.ts';
import type {Decision,Locale,Offer} from './model';
export const historyCopy={
 en:{load:'Historical pillow case',title:'JHT pillows · historical comparison',label:'Historical research · 1 October 2026',intro:'Archived leads, not current quotes. This case starts from recorded evidence; you can edit your own copy.',quantity:'Load recorded quantity',limits:'The queen/king variant, fill, loft and certificate scope remain unresolved. China delivery, handling, tax and last-mile charges were not confirmed. No final delivered price or quality score is available.',weights:'Packing sensitivity: 3.5–4 kg per pair. This is a declared billing scenario, not measured warehouse packing or a confirmed provider rule.',fx:'360 AMD/USD was the personal effective rate used in that run, not a current public exchange rate.',transit:'Btimes advertised 5–7 days in transit. Order-to-door arrival remains unknown. Quickfish had no confirmed time window.',legacy:'The historical rubric was product 35 / supplier 25 / certification 20 / commercial 10 / logistics 10. A readiness value of 40 was not a product-quality score.',sources:'Original public source pages',product:'JHT pillows · two-pack · exact variant unresolved',evidence:'Historical source snapshot; not a current seller quote',notice:'Recorded goods-plus-freight sensitivity only; all missing charges remain unknown.'},
 ru:{load:'Исторический пример с подушками',title:'Подушки JHT · историческое сравнение',label:'Архив исследования · 1 октября 2026',intro:'Архивные данные, не текущие предложения. Пример основан на записанных источниках; свою копию можно редактировать.',quantity:'Загрузить записанное количество',limits:'Вариант queen/king, наполнитель, высота и область сертификата не уточнены. Доставка по Китаю, обработка, налоги и доставка получателю не подтверждены. Итоговой цены и оценки качества нет.',weights:'Сценарий упаковки: 3,5–4 кг на пару. Это допущение для расчёта, не складское измерение и не подтверждённое правило перевозчика.',fx:'360 AMD/USD — личный эффективный курс того расчёта, не текущий публичный курс.',transit:'Btimes указывал 5–7 дней перевозки. Полный срок до двери неизвестен. У Quickfish подтверждённого срока не было.',legacy:'Историческая шкала: продукт 35 / поставщик 25 / сертификация 20 / условия 10 / логистика 10. Готовность 40 не являлась оценкой качества продукта.',sources:'Исходные публичные страницы',product:'JHT, две подушки · вариант не уточнён',evidence:'Исторический снимок источника; не текущее предложение',notice:'Только сценарий стоимости товара и перевозки; остальные расходы неизвестны.'},
 hy:{load:'Բարձերի պատմական օրինակ',title:'JHT բարձեր · պատմական համեմատություն',label:'Հետազոտության արխիվ · 1 հոկտեմբերի 2026',intro:'Արխիվային տվյալներ են, ոչ ընթացիկ առաջարկներ։ Օրինակը հիմնված է գրանցված աղբյուրների վրա․ կարող եք խմբագրել ձեր պատճենը։',quantity:'Բեռնել գրանցված քանակը',limits:'Queen/king տարբերակը, լցանյութը, բարձրությունը և հավաստագրի շրջանակը պարզված չեն։ Չինաստանում առաքումը, մշակումը, հարկերն ու վերջնական առաքումը հաստատված չեն։ Վերջնական գին և որակի միավոր չկան։',weights:'Փաթեթավորման սցենար՝ 3,5–4 կգ մեկ զույգի համար։ Սա հաշվարկային ենթադրություն է, ոչ պահեստում չափված քաշ կամ փոխադրողի հաստատված կանոն։',fx:'360 AMD/USD-ը տվյալ հաշվարկի անձնական արդյունավետ փոխարժեքն էր, ոչ ընթացիկ հանրային փոխարժեք։',transit:'Btimes-ը նշել էր 5–7 օր փոխադրում։ Մինչև դուռ ժամկետն անհայտ է։ Quickfish-ի ժամկետը հաստատված չէր։',legacy:'Պատմական սանդղակը՝ ապրանք 35 / մատակարար 25 / հավաստագրում 20 / պայմաններ 10 / լոգիստիկա 10։ Պատրաստվածության 40 արժեքը ապրանքի որակի միավոր չէր։',sources:'Սկզբնական հանրային աղբյուրներ',product:'JHT երկու բարձ · տարբերակը պարզված չէ',evidence:'Աղբյուրի պատմական պատճեն․ ոչ ընթացիկ գնառաջարկ',notice:'Միայն ապրանքի և փոխադրման հաշվարկային միջակայք․ մյուս ծախսերն անհայտ են։'},
};
export const historicalSources={price:'https://www.alibaba.com/pla/OEKO-TEX-Standard-100-2-Pack-White-King_1601097950097.html?biz=pla&mark=google_shopping&pcy=gb_es&product_id=1601097950097&searchText=bed+pillows',product:'https://www.alibaba.com/product-detail/OEKO-TEX-STANDARD-100-White-2_1601097950097.html',Btimes:'https://www.alibaba.com/showroom/yerevan-shipping-prices.html',Quickfish:'https://www.alibaba.com/countrysearch/CN/air-shipping-to-yerevan-armenia.html'};
/** Bounded public facts from run 2026-10-01-pillows-001; no private addresses or warehouse marks. */
export function historicalPillows(locale:Locale,quantity:2|4=4):Decision{
 const t=historyCopy[locale],pairs=quantity/2;
 const offers:Offer[]=(['Btimes','Quickfish'] as const).map((provider,index)=>{
  const e=emptyEvaluation();
  const source={reference:`Historical listing snapshot P-S22: USD 8.97 per pair; exact variant unresolved. ${historicalSources.price}`,observedAt:'2026-10-01'};
  const fx={reference:'Personal effective exchange rate supplied for this historical run: 360 AMD per USD; not a current market rate.',observedAt:'2026-10-01'};
  e.costs=e.costs.map(c=>c.kind==='goods'?{...c,status:'known',amount:8.97*pairs,currency:'USD',rate:360,rateEvidence:fx,evidence:source,reason:'Recorded listing amount for two-piece packs; variant and availability unconfirmed'}:c.kind==='freight'?{...c,status:'known',amount:(index?7:5.25)*pairs,amountHigh:(index?16:14)*pairs,currency:'USD',rate:360,rateEvidence:fx,evidence:{reference:`Historical catalogue ${provider}: ${historicalSources[provider]}`,observedAt:'2026-10-01'},reason:`Declared sensitivity: 3.5–4 kg per pair × USD ${index?'2–4':'1.50–3.50'}/kg. Provider tariff, rounding and packing unconfirmed; not a cargo quote.`}:c);
  return {id:'historical-'+provider.toLowerCase(),name:t.product,seller:'JHT · '+provider,source:'alibaba',unitPrice:1614.6,packSize:2,quoteQuantity:quantity,shipping:null,fees:null,days:null,quality:'value',url:historicalSources.product,observedAt:'2026-10-01',notes:[t.notice,t.weights,t.fx,t.transit].join('\n'),evidence:'historical',evaluation:e};
 });
 return {version:1,context:'historical-pillows-2026-10-01',title:t.title,quantity,maxQuantity:quantity,budget:40000,maxDays:21,offers};
}
