export type Locale = 'en'|'hy'|'ru';
export type Offer = {id:string;name:string;seller:string;source:'local'|'alibaba'|'temu'|'other';unitPrice:number;packSize:number;quoteQuantity?:number;shipping:number|null;fees:number|null;days:number|null;quality:'premium'|'value'|'budget';url:string;observedAt:string;notes:string;evidence:'sample'|'user'|'quote'};
export type Decision = {version:1;title:string;quantity:number;maxQuantity:number;budget:number;maxDays:number;offers:Offer[]};
export type Result = {offer:Offer;quantity:number;goods:number;subtotal:number;total:number|null;perPiece:number|null;eligible:boolean;reasons:('quantity'|'incomplete'|'budget'|'deadline')[]};
const object=(x:unknown):Record<string,unknown>=>{if(!x||typeof x!=='object'||Array.isArray(x))throw new Error('invalid');return x as Record<string,unknown>};
const str=(x:unknown,max:number)=>{if(typeof x!=='string'||x.length>max)throw new Error('invalid');return x.trim()};
const num=(x:unknown,min:number,max:number,integer=false)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>max||(integer&&!Number.isInteger(x)))throw new Error('invalid');return x};
const choice=<T extends string>(x:unknown,values:readonly T[]):T=>{if(typeof x!=='string'||!values.includes(x as T))throw new Error('invalid');return x as T};
export function validateDecision(input:unknown):Decision {
 const d=object(input); if(d.version!==1)throw new Error('invalid');
 const title=str(d.title,180);if(!title)throw new Error('invalid');
 const quantity=num(d.quantity,1,10000,true),maxQuantity=num(d.maxQuantity,quantity,10000,true);
 if(!Array.isArray(d.offers)||d.offers.length>20)throw new Error('invalid');
 const ids=new Set<string>();
 const offers=d.offers.map((v):Offer=>{const o=object(v),id=str(o.id,80),name=str(o.name,180),seller=str(o.seller,120);if(!id||!name||!seller||ids.has(id))throw new Error('invalid');ids.add(id);
 const url=str(o.url,2000);if(url){let u:URL;try{u=new URL(url)}catch{throw new Error('invalid')};if(u.protocol!=='https:'||u.username||u.password||u.hostname==='localhost'||u.hostname.endsWith('.local')||/^[\d.]+$/.test(u.hostname)||u.hostname.includes(':'))throw new Error('invalid')}
 const observedAt=str(o.observedAt,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(observedAt)||!Number.isFinite(Date.parse(observedAt))||new Date(observedAt).toISOString().slice(0,10)!==observedAt)throw new Error('invalid');
 return {id,name,seller,quoteQuantity:o.quoteQuantity===undefined?Math.ceil(quantity/num(o.packSize,1,10000,true))*num(o.packSize,1,10000,true):num(o.quoteQuantity,1,10000,true),source:choice(o.source,['local','alibaba','temu','other']),unitPrice:num(o.unitPrice,0,100000000),packSize:num(o.packSize,1,10000,true),shipping:o.shipping===null?null:num(o.shipping,0,100000000),fees:o.fees===null?null:num(o.fees,0,100000000),days:o.days===null?null:num(o.days,0,365,true),quality:choice(o.quality,['premium','value','budget']),url,observedAt,notes:str(o.notes,3000),evidence:choice(o.evidence,['sample','user','quote'])};});
 return {version:1,title,quantity,maxQuantity,budget:num(d.budget,1,1000000000),maxDays:num(d.maxDays,1,365,true),offers};
}
export function calculate(d:Decision):Result[]{if(!Number.isInteger(d.quantity)||d.quantity<1||d.quantity>10000||!Number.isInteger(d.maxQuantity)||d.maxQuantity<1||!Number.isFinite(d.budget)||d.budget<=0||!Number.isInteger(d.maxDays)||d.maxDays<1)return [];return d.offers.map(offer=>{const quantity=Math.ceil(d.quantity/offer.packSize)*offer.packSize;const goods=Math.round(offer.unitPrice*quantity*100)/100;const quantityChanged=offer.quoteQuantity!==undefined&&offer.quoteQuantity!==quantity;const subtotal=quantityChanged?goods:Math.round((goods+(offer.shipping??0)+(offer.fees??0))*100)/100;const total=quantityChanged||offer.shipping===null||offer.fees===null?null:subtotal;const reasons:Result['reasons']=[];if(quantity>d.maxQuantity)reasons.push('quantity');if(total===null)reasons.push('incomplete');if(total!==null&&total>d.budget)reasons.push('budget');if(offer.days===null||offer.days>d.maxDays)reasons.push('deadline');return {offer,quantity,goods,subtotal,total,perPiece:total===null?null:total/quantity,eligible:reasons.length===0,reasons};});}
